services:
  - type: web
    name: fontbot
    runtime: python3
    pythonVersion: 3.9
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
      mkdir -p logs
      touch logs/bot.log
    startCommand: |
      python -m bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
    plan: free
    healthCheckPath: /health
    autoDeploy: true 